### ISSUE TITLE
[typed-store] Should `skip_to_last()` return a Result?

### ISSUE THREAD

**Issue by gdanezis** [MystenLabs/mysten-infra#56]
All other `skip_to` iterator functions return a Result, except for `skip_to_last()`. 
https://github.com/MystenLabs/mysten-infra/blob/c7ff7ac8849011ad5d00ab7be86773ffa05f11f7/typed-store/src/rocks/iter.rs#L67-L70

Should this also return a result to detect DB faults?

**Comment by gdanezis** [comment]
@huitseeker you might be the best person to tell me if this is intended or not?

**Comment by huitseeker** [comment]
It is intended, just as the inner `seek_to_first` in the RocksDB API (not exposed in `typed_store`) does not return a `Result`: the reason is that contrarily to `skip`, `skip_prior_to`, there is no chance to not have a key specified as a position by the user, there is no ser/de involved, and at worst we return an empty iterator which position is irrelevant.
